baseURL = "https://math.iisc.ac.in/~gadgil/intro-algebraic-topology-2024/"
languageCode = "en-us"
title = "MA 232: Introduction to Algebraic Topology"
theme = "course"
buildFuture = "true"
[params]
    code = "MA 232"
    course = "Introduction to Algebraic Topology"
    term = "August 2024"
[markup.goldmark.renderer]
unsafe= true